version: '3.7'

services:
  db:
    image: mariadb:5.5.64
    container_name: CDN-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Ab123456
      MYSQL_USER: Gary
      MYSQL_PASSWORD: Ab123456
      MYSQL_DATABASE: defend
      TZ: "Asia/Taipei"
    volumes:
      - ./db_dump:/var/lib/mysql
      - ./config/mysql_conf:/etc/mysql/conf.d
      - ./config/mysql_init:/docker-entrypoint-initdb.d
      - ./db_dump.sh:/db_dump.sh
    
  redis:
    image: redis:6.2.5
    container_name: CDN-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./config/redis:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/redis.conf